config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index', as: :task_index

  get 'tasks/new', to: 'tasks#new', as: :task_new
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy', as: :task_destroy

  get 'tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to task_index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit this task: 📝</h1>

<%= render "form", task: @task %>

<%= link_to 'Back to Tasks', tasks_path %>

app/views/tasks/index.html.erb
<h1>My Tasks ✅</h1>

<ul>
  <% @tasks.each do |task| %>
  <li><%= link_to task.title, task_path(task.id) %> | <%= link_to 'Delete', task_destroy_path(task.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}%></li>
  <% end %>
</ul>

<%= link_to 'Create a task', task_new_path %>

app/views/tasks/new.html.erb
<h1>Add a new Task 🆕</h1>

<%= render "form", task: @task %>

<%= link_to 'Back to Tasks', tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>

<p><%= @task.details %></p>

<p>Done? <%= @task.completed %></p>

<%= link_to 'Back to Tasks', tasks_path %>
<%= link_to 'Edit Task', task_edit_path %>